/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      1000,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320C6670",
            customMemoryMap:
           [          
                ["L2SRAM", 
                     {
                        name: "L2SRAM",
                        base: 0x00800000,                    
                        len: 0x00026000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["MSMCSRAM", 
                     {
                        name: "MSMCSRAM",
                        base: 0x0c000000,                    
                        len: 0x00200000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR", 
                     {
                        name: "DDR",
                        base: 0x80000000,                    
                        len: 0x00200000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR_1", 
                     {
                        name: "DDR_1",
                        base: 0x80200000,                    
                        len: 0x04000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["MSMCSRAM_1", 
                     {
                        name: "MSMCSRAM_1",
                        base: 0x0c200000,                    
                        len: 0x00100000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["MSMCSRAM_2", 
                     {
                        name: "MSMCSRAM_2",
                        base: 0x0c300000,                    
                        len: 0x00100000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["L2SRAM_1", 
                     {
                        name: "L2SRAM_1",
                        base: 0x00826000,                    
                        len: 0x0005a000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],
          l2Mode:"0k",
          l1PMode:"32k",
          l1DMode:"32k",

    });
    
instance :
    
    override config string codeMemory  = "DDR_1";   
    override config string dataMemory  = "L2SRAM";                                
    override config string stackMemory = "L2SRAM";
    
}
